name: CI

on:
  push:
    branches:
      - master

  schedule:
     - cron: '0 19 * * *' # every day at 7pm

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        tag: [
          "6.1.1",
          "6.1.0",
          "6.0.2",
          "6.0.1",
          "6.0.0",
          "5.5.2-1-ubi8",
          "5.5.2",
          "5.5.1-1-ubi8",
          "5.5.0",
          "5.5.0-1-ubi8",
          "5.5.1",
          "5.5.2",
          "5.5.3",
          "5.5.4",
          "5.4.3",
          "5.4.2-1-ubi8",
          "5.4.2",
          "5.4.3-1-ubi8",
          "5.4.1-1-ubi8",
          "5.4.1-2-ubi8",
          "5.4.1",
          "5.4.1-2-ubi8",
          "5.4.0",
          "5.3.2 5.3.1",
          "5.2.3 5.2.2 5.2.1 5.2.0",
          "5.1.3 5.1.2 5.1.1 5.1.0",
          "5.0.3 5.0.2 5.0.1 5.0.0" ]

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u vdesabou --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create images
        run: bash scripts/create-image.sh "${{ matrix.tag }}"

      - name: Create operator images
        run: bash scripts/create-image-operator.sh "${{ matrix.tag }}"

  post-build:
    name: Update README
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update README
        run: |
          COMMIT_MESSAGE=$(./scripts/update-readme.sh "6.1.1")
          echo "commit_msg=$COMMIT_MESSAGE" >> $GITHUB_ENV
      - name: push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: ${{ env.commit_msg }}
          files: ./README.md
          name: Vincent de Saboulin
